### ISSUE TITLE
Badly written

### ISSUE THREAD

**Issue by BSVogler** [advancedresearch/advancedresearch.github.io#26]
> This post is written to be read multiple times, or otherwise you will probably not understand it at all. Actually, you will probably not understand it even after reading it carefully multiple times. I do not expect you to understand it even if you are familiar with path semantics. 

Then it is badly written. Why should I read it?

**Comment by bvssvni** [comment]
Rewrote some parts to explain it better: https://github.com/advancedresearch/advancedresearch.github.io/blob/master/blog/2017-06-03-perfect-intelligence.md

Yeah, it was badly written. I had this realization of there could be an algorithm for perfect problem solving, right after developing the concept of universal existential paths. I could not explain it properly, but I needed to get the idea out. During the months since then the usage of constraints in path semantics has been improved a lot and it is much more clearer to me now, so I should be better at explaining it too!

Still looking for the right tools to express this idea formally.

**Comment by BSVogler** [comment]
okay, cool. Just wanted to give you some feedback, that it was not really encouraging. will look at it.

**Comment by bvssvni** [comment]
It helped refreshing my memory when working on the rewrite, so I also managed to formalize the algorithm: https://github.com/advancedresearch/path_semantics/blob/master/papers-wip/p-vs-np-relative-to-universal-existential-path.pdf

**Comment by bvssvni** [comment]
Closing.
